data:
  raw_path: "data/raw/svg"
  processed_path: "data/processed/png_images"

model:
  input_size: 128
  output_size: 250

training:
  checkpoint_dir: "models/checkpoints/"
  final_model_dir: "models/final/"

